Ci/add sphinx ci script
madeline-scyphers/boa pull request #36
Opened 2022-10-27 04:00 UTC by madeline-scyphers

- [Update ModularMetric to directly save metric_to_eval instead of using…](https://github.com/madeline-scyphers/boa/commit/98b1e908aede600d4360cb4fdc92b320ab535645)  …
  … additional class
  
  ModularMetric use to use a MetricToEval class for json serialization, which wasn't necessary
  at all. Removed that class, and moved the functionality onto ModularMetric. This reduced
  clutter and confusion. Now when you look at a metric, metric.f/metric.metric_to_eval is
  the function, instead of having todo metric.f.func/metric.metric_to_eval.func Which feels
  much easier and cleaner. This also made it easier to make all the built--in metrics
  subclasses, which allowed easier documentation with sphinx rendering.
  
  Added a test that saves and loads a scheduler and resumes an experiment to check that
  the scheduler saving works. Added another test to save an arbitrary callable that is
  passed in. it doesn't work right now, marked as skip and made an issue to get that
  functionality for scheduler saving and loading with arbitrary callables working at
- [Modify api template](https://github.com/madeline-scyphers/boa/commit/11ee4f3b7595c8ee746347c500a1912b5b652601)  …
  Modified code reference api section to not use the
  template as much, and allowing each module to be generated
  when it is needed in the api section. This is a tradeoff of
  convencience for more customizability and a better doc design
- [More docstring updates, fix broken rst links](https://github.com/madeline-scyphers/boa/commit/8cdcef82d3d8325fdc0f2d528d86f4257f12d4e6)  …
  Add docutils func that adds a reference to the relative
  __init__.py of all files __doc__ in each submodule
  
  change sphinx configuration to be nitpicky which revealed a bunch
  of broken sphinx links which were then fixed (except ax and
  botorch links which can't be fixed right now because
  they don't build sphinx in a normal way.
  see https://github.com/facebook/Ax/issues/1227
  and see https://github.com/pytorch/botorch/issues/1464
  for more info on when ax and botroch can be linked).
- [Add examples, boa cli info, config info](https://github.com/madeline-scyphers/boa/commit/d74f7bdc1d017687172476a55bd7cc4cec4d26ec)
  Add example cli boa script with output and basic instructions on how to do boa cli

2022-11-05 17:12 UTC, jemissik commented on boa/controller.py
> +            (defaults to what is specified in the config,
Probably we need to add some examples/instructions about these options to the configuration guide

2022-11-05 17:29 UTC, jemissik commented on boa/metrics/__init__.py
> +
We should add a note here that points to where users need to look if they are using custom metrics.

2022-11-05 17:34 UTC, jemissik commented on boa/metrics/__init__.py
> +
And also add mention of this to the user guide. I don't see anywhere obvious that points out that you can pass your own metric through directly if you need more customization

2022-11-05 19:29 UTC, jemissik commented on docs/user_guide/getting_started.rst
>  Clone the boa repository from `boa's GitHub page <https://github.com/madeline-scyphers/boa>`_.
Maybe should make a note to fork the repo, if it's for contributors?

2022-11-05 19:48 UTC, jemissik requested changes
I pushed a few edits to the docs, and fixed the refs in the notebooks

2022-11-05 23:43 UTC, jemissik commented on docs/user_guide/getting_started.rst
> +    conda install botorch -c pytorch-nightly -c pytorch -c gpytorch -c conda-forge
Needs updating for x86?

2022-11-06 00:14 UTC, madeline-scyphers commented on docs/user_guide/getting_started.rst
> +    conda install botorch -c pytorch-nightly -c pytorch -c gpytorch -c conda-forge
Good catch

2022-11-06 00:24 UTC, jemissik approved these changes

2022-11-06 00:25 UTC, merged